# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacosBatteryExporter < Formula
  desc "Prometheus exporter for detailed battery metrics on macOS."
  homepage "https://github.com/jimeh/macos-battery-exporter"
  version "0.0.5"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/jimeh/macos-battery-exporter/releases/download/v0.0.5/macos-battery-exporter-0.0.5_darwin_universal.tar.gz"
    sha256 "681a25f6aaca6f78e523fae0bff4ec667eaff6fa30bd845b939c32b761a82d9e"

    def install
      bin.install "macos-battery-exporter"
    end
  end

  service do
    run [bin/"macos-battery-exporter", "-s"]
  end

  test do
    system "#{bin}/macos-battery-exporter -v"
  end
end
