# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacosBatteryExporter < Formula
  desc "Prometheus exporter for detailed battery metrics on macOS."
  homepage "https://github.com/jimeh/macos-battery-exporter"
  version "0.0.6"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/jimeh/macos-battery-exporter/releases/download/v0.0.6/macos-battery-exporter-0.0.6_darwin_universal.tar.gz"
    sha256 "08099095c1c64038dbc5078eaed052455fbfacebb25ce96e9e0f168beda27b77"

    def install
      bin.install "macos-battery-exporter"
    end
  end

  service do
    run [bin/"macos-battery-exporter", "-s"]
  end

  test do
    system "#{bin}/macos-battery-exporter -v"
  end
end
