# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MacosBatteryExporter < Formula
  desc "Prometheus exporter for detailed battery metrics on macOS."
  homepage "https://github.com/jimeh/macos-battery-exporter"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/jimeh/macos-battery-exporter/releases/download/v0.0.3/macos-battery-exporter-0.0.3_darwin_universal.tar.gz"
    sha256 "4101d31b5d8c242f00fcf17c4fddbf0961f2467b0d65ed59837ad1875a2ea84e"

    def install
      bin.install "macos-battery-exporter"
    end
  end

  service do
    run [bin/"macos-battery-exporter", "-s"]
  end

  test do
    system "#{bin}/macos-battery-exporter -v"
  end
end
